---
title: "Pathway Analysis Introduction"
output:   
  html_notebook:
    toc: true
    toc_float: true
    number_sections: true
---

## Background

Over-representation analysis (ORA) is a method of pathway or gene set analysis
where one can ask if a set of genes (e.g., those differentially expressed
using some cutoff) shares more or less genes with gene sets/pathways than
we would expect at random.
The other methodologies introduced throughout this module such as QuSAGE and
GSEA can require more samples than a different expression analysis.
For instance, the sample label permutation step of GSEA is reported to
perform poorly with 7 samples or less in each group
([](https://doi.org/10.1093/nar/gkt660)).
It is not uncommon to have n ~ 3 for each group in a treatment-control
transcriptomic study, at which point identifying differentially expressed genes
is possible.
If you are interested in performing pathway analysis on a small study, ORA may
be your best bet.
There are some limitations to ORA methods to be aware such as ignoring
gene-gene correlation.
See [](https://doi.org/10.1371/journal.pcbi.1002375) 
to learn more about the different types of pathway analysis and their
limitations.

