name: Build, Render, and Push

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  push:
    branches: [ staging, master, jashapiro/dont-push-staging-docker ]

jobs:
  # This workflow contains a single job called "build-all"
  build-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          # get the full repo
          fetch-depth: 0
          # use alexslemonade-docs-bot
          token: ${{ secrets.DOCS_BOT_GITHUB_TOKEN }}

      - name: Checkout pages branch and sync with changes
        run: |
          echo $GITHUB_REF
          if [ $GITHUB_REF == 'refs/heads/master' ]
          then
            pages_branch="gh-pages"
          elif [ $GITHUB_REF == 'refs/heads/staging' ]
          then
            pages_branch="gh-pages-stages"
          fi
          git config --local user.email "actions@github.com"
          git config --local user.name "Alex's Lemonade Docs Bot"
          git checkout $pages_branch
          git merge -s recursive --strategy-option=theirs ${{ github.event.after }}

      # Login to Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Build docker image and push if this is master
      - name: Build and Push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          file: docker/Dockerfile
          tags: ccdl/refinebio-examples:latest
      # for staging, we just want to build, but not push
      - name: Build and Load Docker image
        if: github.ref == 'refs/heads/staging'
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: docker
          file: docker/Dockerfile
          tags: ccdl/refinebio-examples:latest
      # download data
      - name: Download data
        run: bash scripts/download-data.sh

      - name: Render all pages to html
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          ccdl/refinebio-examples \
          snakemake --cores 2 --forceall

      # If we are on the staging branch, do not publish to github pages
      - name: Commit changed html back to non-public pages
        if: github.ref == 'refs/heads/staging'
        run: |
          git add -A
          git commit -m 'Render html, do not publish' || echo "No changes to commit"
          git push origin gh-pages-stages || echo "No changes to push"

      # If we are on the master branch, publish to github pages!
      - name: Commit changed html to public pages
        if: github.ref == 'refs/heads/master'
        run: |
          git add -A
          git commit -m 'Render html and publish' || echo "No changes to commit"
          git push origin gh-pages || echo "No changes to push"
