name: Build and Push

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  push:
    branches: [ master, jashapiro/gha-snakemake ]

jobs:
  # This workflow contains a single job called "build-push"
  build-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      # Test if Dockerfile has changed 
      - name: check_docker
        env: 
          before: ${{ github.event.push.before }}
        run: echo $before
      # Login to dockerhub
      - name: Login to DockerHub
        if: ${{ steps.check_docker.outputs.changed }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    #   # Build docker image (We are not using caching here to force a clean build)
    #   - name: Build and Push Docker image
    #     uses: docker/build-push-action@v2
    #     with:
    #       push: true
    #       context: docker
    #       file: docker/Dockerfile
    #       tags: ccdl/refinebio-examples:latest




