name: Build Docker

# Controls when the action will run. Triggers the workflow for a pull request for 
# master
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Test if Dockerfile has changed
      # sets steps.check_docker.outputs.changed to 1 if the Dockerfile has changed, 0 otherwise
      - name: Check Dockerfile for changes
        id: check_docker
        env:
          BEFORE: ${{ github.base_ref }}
        run: |
          git diff-index --name-only origin/$BEFORE > changes.txt
          if grep "docker/Dockerfile" changes.txt ; then
            echo "Dockerfile changed"
            echo "::set-output name=changed::1"
          else
            echo "No change to Dockerfile"
            echo "::set-output name=changed::0"
          fi
          rm changes.txt

      # set up Docker build
      - name: Set up Docker Buildx
        if: steps.check_docker.outputs.changed == 1
        uses: docker/setup-buildx-action@v1

      # setup layer cache
      - name: Cache Docker layers
        if: steps.check_docker.outputs.changed == 1
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build docker image
      - name: Build Docker image
        if: steps.check_docker.outputs.changed == 1
        uses: docker/build-push-action@v2
        with:
          push: false
          context: docker
          file: docker/Dockerfile
          tags: ccdl/refinebio-examples:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
