name: Build, Render, and Push

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  push:
    branches: [ staging, master ]
  pull_request:
    branches: [ staging, master ]

jobs:
  # This workflow contains a single job called "build-all"
  build-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
        with:
          # get the full repo
          fetch-depth: 0
          # use alexslemonade-docs-bot
          token: ${{ secrets.DOCS_BOT_GITHUB_TOKEN }}

      - name: Checkout pages branch and sync with changes
        run: |
          if [github.ref == 'refs/heads/master']
          then
            pages_branch=gh-pages
          elif [github.ref == 'refs/heads/staging']
            pages_branch=gh-pages-stages
          fi 
          echo $pages_branch
          git config --local user.email "actions@github.com"
          git config --local user.name "Alex's Lemonade Docs Bot"
          git checkout $pages_branch
          git merge -s recursive --strategy-option=theirs ${{ github.event.after }}

      # Test if Dockerfile has changed
      # sets steps.check_docker.outputs.changed to 1 if the Dockerfile has changed, 0 otherwise
      - name: Check Dockerfile for changes
        id: check_docker
        env:
          BEFORE: ${{ github.event.before }}
        run: |
          git diff-index --name-only $BEFORE > changes.txt
          if grep "docker/Dockerfile" changes.txt ; then
            echo "Dockerfile changed"
            echo "::set-output name=changed::1"
          else
            echo "No change to Dockerfile"
            echo "::set-output name=changed::0"
          fi
          rm changes.txt

      # Login to Dockerhub
      - name: Login to DockerHub
        if: steps.check_docker.outputs.changed == 1
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # set up Docker build
      - name: Set up Docker Buildx
        if: steps.check_docker.outputs.changed == 1
        uses: docker/setup-buildx-action@v1
      # Build docker image (We are not using caching here to force a clean build)
      - name: Build and Push Docker image
        if: steps.check_docker.outputs.changed == 1
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker
          file: docker/Dockerfile
          tags: ccdl/refinebio-examples:latest
      # download data
      - name: Download data
        run: bash scripts/download-data.sh

      - name: Render all pages to html
        run: |
          docker run \
          --mount type=bind,target=/home/rstudio,source=$PWD \
          ccdl/refinebio-examples \
          snakemake --cores 2 --forceall

      # If we are on the staging branch, do not publish to github pages
      - name: Commit changed html back to non-public pages
        if: github.ref == 'refs/heads/staging'
        run: |
          git add -A
          git commit -m 'Render html, do not publish' || echo "No changes to commit"
          git push origin gh-pages-stages || echo "No changes to push"

      # If we are on the master branch, publish to github pages!
      - name: Commit changed html to public pages
        if: github.ref == 'refs/heads/master'
        run: |
          git add -A
          git commit -m 'Render html and publish' || echo "No changes to commit"
          git push origin gh-pages || echo "No changes to push"
